import { useEffect, useMemo, useState } from 'react'
import api from './api'

const fallback = {
  summary: { active_routes: 8, active_vehicles: 42, on_time_rate: 91.8, avg_wait: 7.4, ridership_today: 12840, delay_alerts: 3, trend: [48, 61, 56, 76, 68, 88, 80, 96, 77, 91, 73, 85] },
  routes: [
    { id: 'R12', name: 'Central — Riverside', status: 'On time', occupancy: 68, eta: 4, color: '#65d9b1', buses: 6 },
    { id: 'R08', name: 'University — Midtown', status: 'On time', occupancy: 82, eta: 7, color: '#8c8bff', buses: 8 },
    { id: 'R21', name: 'Airport — Central', status: 'Delayed', occupancy: 94, eta: 12, color: '#ffb66d', buses: 5 },
    { id: 'R04', name: 'North Park — Market', status: 'On time', occupancy: 47, eta: 3, color: '#f28eae', buses: 7 },
    { id: 'R16', name: 'Harbor — Tech District', status: 'Rerouted', occupancy: 73, eta: 9, color: '#63bdf3', buses: 4 },
  ],
  demand: [408, 324, 288, 384, 576, 852, 1056, 948, 744, 636, 696, 888],
  alerts: [
    { severity: 'high', title: 'High passenger load', detail: 'R21 · Airport — Central · 94% capacity', time: '4 min ago' },
    { severity: 'medium', title: 'Traffic delay detected', detail: 'R08 · University — Midtown · +8 min', time: '12 min ago' },
    { severity: 'low', title: 'Route diversion active', detail: 'R16 · Harbor — Tech District · Market St', time: '26 min ago' },
  ],
}

function Icon({ name, size = 18 }) {
  const paths = { grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>, route: <><circle cx="6" cy="18" r="3"/><circle cx="18" cy="6" r="3"/><path d="M9 18h3a3 3 0 0 0 3-3V9a3 3 0 0 1 3-3"/></>, bus: <><rect x="3" y="4" width="18" height="15" rx="3"/><path d="M3 11h18M7 19v2m10-2v2M7 8h.01M17 8h.01"/></>, chart: <><path d="M3 3v18h18M8 15l4-5 4 3 5-7"/></>, alert: <><path d="m10.3 3.9-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3l-8-14a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4m0 4h.01"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="m19.4 15 .1.1 1.4 1.1-1.4 2.4-1.7-.6a8 8 0 0 1-1.7 1l-.3 1.8h-2.8l-.3-1.8a8 8 0 0 1-1.7-1l-1.7.6-1.4-2.4 1.4-1.1a8 8 0 0 1 0-2l-1.4-1.1 1.4-2.4 1.7.6a8 8 0 0 1 1.7-1l.3-1.8h2.8l.3 1.8a8 8 0 0 1 1.7 1l1.7-.6 1.4 2.4-1.4 1.1a8 8 0 0 1 0 2Z"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, arrow: <><path d="M7 17 17 7M7 7h10v10"/></>, download: <><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4m4-5 5 5 5-5m-5 5V3"/></> }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

function Sparkline({ values, color = '#67d8b0', height = 42 }) {
  const max = Math.max(...values), min = Math.min(...values), range = max - min || 1
  const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${height - 3 - ((v - min) / range) * (height - 8)}`).join(' ')
  return <svg className="sparkline" viewBox={`0 0 100 ${height}`} preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="2.4" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg>
}

function DemandChart({ values }) {
  const labels = ['6a', '7a', '8a', '9a', '10a', '11a', '12p', '1p', '2p', '3p', '4p', '5p']
  return <div className="demand-chart"><div className="chart-y"><span>1.2k</span><span>900</span><span>600</span><span>300</span><span>0</span></div><div className="chart-main"><div className="chart-lines"><i/><i/><i/><i/><i/></div><div className="bars">{values.map((value, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${Math.min(100, value / 12)}%` }} title={`${value} passengers`} /></div>)}</div><div className="chart-x">{labels.map(x => <span key={x}>{x}</span>)}</div></div></div>
}

function MapPanel({ routes }) {
  return <div className="map"><div className="map-grid"/><svg className="map-svg" viewBox="0 0 600 330" preserveAspectRatio="xMidYMid slice"><path className="road" d="M-20 255 112 205 211 228 331 165 413 179 620 94M26 36 118 88 187 74 283 131 367 106 481 146 604 123M55 350 132 286 191 293 273 235 354 253 428 205 525 224 620 189M284-20 265 72 302 133 279 202 310 269 302 350M455-20 421 62 451 109 419 165 445 231 408 350"/><path className="route-line route-a" d="M56 263 144 221 221 226 302 178 372 183 475 140 557 113"/><path className="route-line route-b" d="M93 55 163 99 220 88 302 137 375 114 467 149 530 169"/><path className="route-line route-c" d="M117 303 184 273 245 246 304 178 355 149 411 106 438 51"/><path className="route-line route-d" d="M183 74 210 122 242 156 302 178 352 217 405 249 486 238"/><path className="route-muted" d="M43 155 118 145 179 170 221 226 246 246M302 178 319 93 375 45M355 149 452 193 525 224"/><circle className="stop" cx="144" cy="221" r="4"/><circle className="stop" cx="302" cy="178" r="5"/><circle className="stop" cx="475" cy="140" r="4"/><circle className="stop" cx="210" cy="122" r="4"/><circle className="stop" cx="405" cy="249" r="4"/><circle className="stop" cx="117" cy="303" r="4"/><circle className="map-dot" cx="372" cy="183" r="7"/><circle className="map-dot" cx="302" cy="137" r="7"/><circle className="map-dot orange" cx="411" cy="106" r="7"/><circle className="map-dot" cx="245" cy="246" r="7"/></svg><div className="map-label label-one">Central Station</div><div className="map-label label-two">Midtown</div><div className="map-label label-three">Riverside</div><div className="map-controls"><button aria-label="Zoom in">+</button><button aria-label="Zoom out">−</button></div><div className="map-legend"><span><i className="legend-live"/>Route lines</span><span><i className="legend-stop"/>Stops</span></div><div className="map-status">Illustrative network map</div></div>
}

export default function App() {
  const now = new Date()
  const greeting = now.getHours() < 12 ? 'Good morning' : now.getHours() < 17 ? 'Good afternoon' : 'Good evening'
  const [data, setData] = useState(fallback)
  const [demandInfo, setDemandInfo] = useState({ source: 'sample_profile', observations: 0 })
  const [forecastInfo, setForecastInfo] = useState(null)
  const [section, setSection] = useState('Overview')
  const [search, setSearch] = useState('')
  const [connection, setConnection] = useState('connecting')
  const [updated, setUpdated] = useState(new Date())
  useEffect(() => { let alive = true; const refresh = async () => { try { const [s, r, a, d] = await Promise.all([api.get('/api/dashboard/summary'), api.get('/api/routes'), api.get('/api/alerts'), api.get('/api/demand')]); if (alive) { setData({ summary: s.data, routes: r.data, alerts: a.data, demand: d.data.values }); setDemandInfo({ source: d.data.source, observations: d.data.observations }); setConnection('online'); setUpdated(new Date()) } } catch { if (alive) setConnection('demo') } }; refresh(); const timer = setInterval(refresh, 30000); return () => { alive = false; clearInterval(timer) } }, [])
  useEffect(() => { let alive = true; const route = data.routes[0]; if (connection !== 'online' || !route) { setForecastInfo(null); return () => { alive = false } } const target = new Date(); target.setMinutes(0, 0, 0); target.setHours(target.getHours() + 1); api.post('/api/forecast', { route_id: route.id, target_at: target.toISOString(), weather: 'clear', event: false }).then(r => { if (alive) setForecastInfo(r.data) }).catch(() => { if (alive) setForecastInfo(null) }); return () => { alive = false } }, [connection, data.routes])
  const shownRoutes = useMemo(() => data.routes.filter(r => `${r.id} ${r.name}`.toLowerCase().includes(search.toLowerCase())), [data.routes, search])
  const nav = [{ label: 'Overview', icon: 'grid' }, { label: 'Routes', icon: 'route' }, { label: 'Fleet', icon: 'bus' }, { label: 'Demand forecast', icon: 'chart' }, { label: 'Alerts', icon: 'alert', count: data.alerts.length }]
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Icon name="route" size={21}/></div><div><strong>TransitIQ</strong><small>OPERATIONS CENTER</small></div><button className="collapse" aria-label="Collapse menu">‹</button></div><div className="workspace"><div className="city-icon">SF</div><div><b>San Francisco</b><small>Transit network</small></div><span>⌄</span></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(item => <button key={item.label} className={`nav-item ${section === item.label ? 'active' : ''}`} onClick={() => setSection(item.label)}><Icon name={item.icon}/><span>{item.label}</span>{item.count && <em>{item.count}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="system-card"><div className="system-title"><span className={`status-dot ${connection === 'online' ? 'green' : ''}`}/><b>{connection === 'online' ? 'API connected' : connection === 'demo' ? 'Demo data active' : 'Connecting to API'}</b></div><p>{connection === 'online' ? 'Showing available observations' : 'Showing sample network data'}</p><div className="system-track"><i/></div></div><button className="nav-item settings" onClick={() => setSection('Settings')}><Icon name="settings"/><span>Settings</span></button><div className="profile"><div className="avatar">JD</div><div><b>Jordan Davis</b><small>Transit operator</small></div><span>···</span></div></div></aside>
    <main className="main"><header className="topbar"><div className="crumb">Operations <span>/</span> <b>{section}</b></div><div className="top-actions"><div className="live-clock"><span className={`pulse ${connection === 'online' ? '' : 'offline'}`}/> {connection === 'online' ? 'API CONNECTED' : 'SAMPLE PREVIEW'} <span className="clock-sep">·</span> {updated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</div><button className="icon-button" aria-label="Search"><Icon name="search"/></button><button className="icon-button notification" aria-label="Notifications"><Icon name="alert"/><i/></button><div className="top-avatar">JD</div></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">{now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).toUpperCase()} <span>·</span> {now.getHours() < 12 ? 'MORNING' : now.getHours() < 17 ? 'AFTERNOON' : 'EVENING'} SHIFT</div><h1>{section === 'Overview' ? `${greeting}, Jordan` : section}</h1><p>Here’s what’s happening across your network today.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => window.print()}><Icon name="download" size={16}/> Export report</button><button className="button primary" onClick={() => setSection('Routes')}><span>＋</span> Manage routes</button></div></div>
      <section className="metrics"><article className="metric-card"><div className="metric-top"><span>ACTIVE ROUTES</span><span className="metric-icon violet"><Icon name="route"/></span></div><div className="metric-value">{data.summary.active_routes}<small> routes</small></div><div className="metric-foot"><span>{connection === 'online' ? 'Registered in route catalog' : 'Sample network'}</span>{connection !== 'online' && <Sparkline values={[4,5,5,6,6,7,7,8]} color="#9a92ff" height={34}/>}</div></article><article className="metric-card"><div className="metric-top"><span>ON-TIME PERFORMANCE</span><span className="metric-icon mint"><Icon name="clock"/></span></div><div className="metric-value">{data.summary.on_time_rate ?? '—'}{data.summary.on_time_rate != null && <small>%</small>}</div><div className="metric-foot"><span>{connection === 'online' ? 'Based on reported delays' : 'Sample metric'}</span>{connection !== 'online' && <Sparkline values={[61,68,66,72,70,81,79,89]} color="#66d6b0" height={34}/>}</div></article><article className="metric-card"><div className="metric-top"><span>PASSENGERS TODAY</span><span className="metric-icon blue"><Icon name="bus"/></span></div><div className="metric-value">{data.summary.ridership_today.toLocaleString()}</div><div className="metric-foot"><span>{connection === 'online' ? `${data.summary.observation_count || 0} recent observations` : 'Sample metric'}</span>{connection !== 'online' && <Sparkline values={[35,42,38,52,61,56,74,88]} color="#6bbbf6" height={34}/>}</div></article><article className="metric-card"><div className="metric-top"><span>AVG. REPORTED DELAY</span><span className="metric-icon amber"><Icon name="clock"/></span></div><div className="metric-value">{data.summary.avg_delay ?? '—'}{data.summary.avg_delay != null && <small> min</small>}</div><div className="metric-foot"><span>{connection === 'online' ? 'From recorded observations' : 'Sample metric'}</span>{connection !== 'online' && <Sparkline values={[84,77,81,62,68,55,57,43]} color="#f3b86e" height={34}/>}</div></article></section>
      <div className="dashboard-grid"><section className="panel network-panel"><div className="panel-heading"><div><h2>Network overview</h2><p>Illustrative route map · live vehicle locations require a telemetry feed</p></div><button className="select-button">Today <span>⌄</span></button></div><MapPanel routes={data.routes}/></section><section className="panel forecast-panel"><div className="panel-heading"><div><h2>Passenger demand</h2><p>{connection === 'online' ? `Hourly network averages · ${forecastInfo?.route_id || 'route forecast pending'}` : 'Sample hourly demand profile'}</p></div><button className="more-button" aria-label="More options">···</button></div><div className="forecast-kpi"><div><strong>{forecastInfo?.predicted_passengers ?? '—'}</strong><small> forecast passengers · next hour</small></div></div><DemandChart values={data.demand}/><div className="chart-legend"><span><i className="observed-key"/> Historical hourly average</span><small>{demandInfo.observations} observations</small></div><div className="model-note"><span className="model-spark">✳</span><span><b>{forecastInfo ? `${forecastInfo.route_id} · ${forecastInfo.method === 'random_forest' ? 'ML forecast' : 'Historical baseline'} · ${forecastInfo.validation_mae != null ? `MAE ${forecastInfo.validation_mae} passengers` : `${forecastInfo.training_observations} training observations`}` : 'Forecast unavailable'}</b><small>{forecastInfo?.message || (forecastInfo?.validation_samples ? `Chronological validation on ${forecastInfo.validation_samples} observations` : connection === 'online' ? 'Add ridership observations to generate forecasts' : 'Sample data shown · connect the API for predictions')}</small></span><button onClick={() => setSection('Demand forecast')}><Icon name="arrow" size={16}/></button></div></section></div>
      <div className="lower-grid"><section className="panel routes-panel"><div className="panel-heading"><div><h2>Active routes <span className="heading-count">{data.summary.active_routes}</span></h2><p>Service status from available transit feeds</p></div><button className="text-link" onClick={() => setSection('Routes')}>View all routes <Icon name="arrow" size={14}/></button></div><div className="table-tools"><label className="search-box"><Icon name="search" size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search routes..."/></label><button className="filter-button">All status <span>⌄</span></button></div><div className="route-table"><div className="table-row table-head"><span>ROUTE</span><span>STATUS</span><span>OCCUPANCY</span><span>NEXT ARRIVAL</span></div>{shownRoutes.slice(0, 5).map(route => <div className="table-row" key={route.id}><span className="route-name"><i style={{ background: route.color }}/><b>{route.id}</b><small>{route.name}</small></span><span><i className={`status-pill ${['Awaiting telemetry', 'No delay data', 'Telemetry stale'].includes(route.status) ? 'awaiting' : route.status.toLowerCase()}`}>{route.status}</i></span><span className="occupancy">{route.occupancy == null ? <small>—</small> : <><span className="occupancy-track"><i style={{ width: `${route.occupancy}%`, background: route.occupancy > 90 ? '#f39b67' : route.occupancy > 80 ? '#e9bc62' : '#64cfaa' }}/></span><small>{route.occupancy}%</small></>}</span><span className="arrival">{route.eta == null ? '—' : `${route.eta} min`}</span></div>)}</div></section><section className="panel alerts-panel"><div className="panel-heading"><div><h2>Service alerts <span className="alert-count">{data.alerts.length}</span></h2><p>{connection === 'online' ? 'Generated from recorded service observations' : 'Sample alert feed'}</p></div><button className="more-button" aria-label="More options">···</button></div><div className="alerts-list">{data.alerts.length ? data.alerts.map((alert, i) => <div className="alert-row" key={i}><div className={`alert-symbol ${alert.severity}`}><Icon name="alert" size={16}/></div><div className="alert-copy"><b>{alert.title}</b><p>{alert.detail}</p><small>{alert.time}</small></div><button className="alert-arrow" aria-label="Open alert"><Icon name="arrow" size={15}/></button></div>) : <div className="empty-alerts">{connection === 'online' ? 'No service alerts from the available observations.' : 'No sample alerts.'}</div>}</div><button className="all-alerts" onClick={() => setSection('Alerts')}>View all alerts <Icon name="arrow" size={14}/></button></section></div>
      <footer><span>TransitIQ Operations Platform <i>·</i> Data refreshes every 30 seconds</span><span><i className={`status-dot ${connection === 'online' ? 'green' : ''}`}/> {connection === 'online' ? 'API connected · telemetry is observation-based' : 'Sample preview'} <i>·</i> Last updated {updated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></footer></div></main></div>
}
